title:              I Know The Pieces Fit
email:              dilay.e.celik@hotmail.com
description:        Personal insights into the challenges of life that bring us together
author:             Dilay Eylul Celik
baseurl:            "https://startbootstrap.github.io" 
url:                "https://dilayeylul.github.io"

# Social Profiles
instagram_username: d.e.celik 
linkedin_username: dilay-eylul-celik

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
